// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { GamesGetGamesData, GamesGetGamesResponse, GamesGetGamesTodayResponse, GamesGetGameSocialPostsData, GamesGetGameSocialPostsResponse, HealthGetHealthResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse } from './types.gen';

export class GamesService {
    /**
     * Get Games
     * Get NCAA Men's Basketball games for a specific date.
     *
     * Note: When date parameter is omitted, uses current date in UTC timezone.
     * Frontend should handle timezone conversion for user display.
     *
     * Args:
     * session: Database session (injected)
     * date_param: Optional date in YYYY-MM-DD format (defaults to today in UTC)
     *
     * Returns:
     * GameListResponse with list of games and metadata
     *
     * Raises:
     * HTTPException 400: Invalid date format
     * HTTPException 500: Database error
     * @param data The data for the request.
     * @param data.date Date in YYYY-MM-DD format (defaults to today in UTC)
     * @returns GameListResponse Successful Response
     * @throws ApiError
     */
    public static getGames(data: GamesGetGamesData = {}): CancelablePromise<GamesGetGamesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/games',
            query: {
                date: data.date
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * @deprecated
     * Get Games Today
     * Get today's NCAA Men's Basketball games (convenience endpoint).
     *
     * **DEPRECATED:** This endpoint uses UTC timezone to determine "today", which
     * causes incorrect results for users in western timezones during evening hours.
     *
     * **Recommended:** Use `GET /games?date={YYYY-MM-DD}` instead, calculating the
     * date parameter in the user's local timezone on the client side.
     *
     * Example (JavaScript):
     * ```js
     * // Get local date in YYYY-MM-DD format (not UTC!)
     * const localDate = new Date().toLocaleDateString('en-CA');  // en-CA uses YYYY-MM-DD
     * fetch(`/api/v1/games?date=${localDate}`);
     *
     * // Or with date-fns:
     * // import { format } from 'date-fns';
     * // const localDate = format(new Date(), 'yyyy-MM-dd');
     * ```
     *
     * Args:
     * session: Database session (injected)
     *
     * Returns:
     * GameListResponse with list of today's games (UTC) and metadata
     * @returns GameListResponse Successful Response
     * @throws ApiError
     */
    public static getGamesToday(): CancelablePromise<GamesGetGamesTodayResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/games/today'
        });
    }
    
    /**
     * Get Game Social Posts
     * Get social posts associated with a specific game (Story 4-10).
     *
     * Returns posts ordered by engagement_score DESC (most viral first).
     * Includes sentiment classification and source URLs for Reddit/Bluesky.
     *
     * Args:
     * game_id: Natural key for game (e.g., "ncaam_401525257")
     * session: Database session (injected)
     * limit: Maximum number of posts to return (default 10, max 50)
     *
     * Returns:
     * SocialPostListResponse with posts, total_count, and game_id
     *
     * Raises:
     * HTTPException 404: Game not found
     * HTTPException 500: Database error
     * @param data The data for the request.
     * @param data.gameId
     * @param data.limit Max posts to return (1-50)
     * @returns SocialPostListResponse Successful Response
     * @throws ApiError
     */
    public static getGameSocialPosts(data: GamesGetGameSocialPostsData): CancelablePromise<GamesGetGameSocialPostsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/games/{game_id}/social-posts',
            path: {
                game_id: data.gameId
            },
            query: {
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
}

export class HealthService {
    /**
     * Get Health
     * System health check endpoint.
     *
     * Validates database connectivity and returns system status.
     * Used by GitHub Actions smoke test and future monitoring.
     *
     * Returns:
     * HealthCheckResponse: System health status with database connectivity
     *
     * Raises:
     * HTTPException: 503 if database unreachable
     * @returns HealthCheckResponse Successful Response
     * @throws ApiError
     */
    public static getHealth(): CancelablePromise<HealthGetHealthResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/health',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
    
}