// This file is auto-generated by @hey-api/openapi-ts

/**
 * Response schema for games list endpoint.
 */
export type GameListResponse = {
    /**
     * List of games
     */
    games: Array<GamePublic>;
    /**
     * Total number of games returned
     */
    total_count: number;
    /**
     * Response generation timestamp (UTC)
     */
    generated_at: string;
    /**
     * Requested date in YYYY-MM-DD format
     */
    requested_date: string;
};

/**
 * Public game response with team details.
 */
export type GamePublic = {
    /**
     * Surrogate key for game fact
     */
    game_key: number;
    /**
     * Natural key (sport_api_id format)
     */
    game_id: string;
    /**
     * Game date (timezone-aware)
     */
    game_date: string;
    /**
     * Game start time (timezone-aware)
     */
    game_start_time?: (string | null);
    /**
     * Game status (scheduled, in_progress, final)
     */
    game_status?: (string | null);
    /**
     * Home team details
     */
    home_team: TeamInfo;
    /**
     * Away team details
     */
    away_team: TeamInfo;
    /**
     * Home team score
     */
    home_score?: number;
    /**
     * Away team score
     */
    away_score?: number;
};

/**
 * Health check response with system status and database connectivity.
 */
export type HealthCheckResponse = {
    /**
     * Overall system health: healthy, degraded, unhealthy
     */
    status: string;
    /**
     * API version string
     */
    version: string;
    /**
     * Database connectivity: connected, disconnected
     */
    database: string;
    /**
     * Process uptime in seconds
     */
    uptime_seconds: number;
    /**
     * Health check timestamp (UTC)
     */
    timestamp: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Generic message response model.
 */
export type Message = {
    message: string;
};

/**
 * Team information for game responses.
 */
export type TeamInfo = {
    /**
     * Surrogate key for team dimension
     */
    team_key: number;
    /**
     * Natural key (sport_slug format)
     */
    team_id: string;
    /**
     * Full team name
     */
    team_name: string;
    /**
     * Conference or division name
     */
    team_group_name?: (string | null);
    /**
     * Primary team color (hex)
     */
    primary_color?: (string | null);
    /**
     * Secondary team color (hex)
     */
    secondary_color?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type GamesGetGamesData = {
    /**
     * Date in YYYY-MM-DD format (defaults to today in UTC)
     */
    date?: (string | null);
};

export type GamesGetGamesResponse = (GameListResponse);

export type GamesGetGamesTodayResponse = (GameListResponse);

export type HealthGetHealthResponse = (HealthCheckResponse);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);