"""Create multi-sport schema

Revision ID: 29a82f0b5d5b
Revises: 001_initialize
Create Date: 2025-11-10 03:08:11.508996

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '29a82f0b5d5b'
down_revision = '001_initialize'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_groups',
    sa.Column('team_group_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('team_group_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sport', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('group_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent_group_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_group_id'], ['team_groups.team_group_id'], ),
    sa.PrimaryKeyConstraint('team_group_id')
    )
    op.create_index(op.f('ix_team_groups_sport'), 'team_groups', ['sport'], unique=False)
    op.create_table('teams',
    sa.Column('team_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sport', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('team_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('team_abbr', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('team_group_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('primary_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('secondary_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('aliases', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_group_id'], ['team_groups.team_group_id'], ),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_index(op.f('ix_teams_sport'), 'teams', ['sport'], unique=False)
    op.create_table('games',
    sa.Column('game_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sport', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('game_date', sa.DateTime(), nullable=False),
    sa.Column('home_team_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('away_team_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.Column('away_score', sa.Integer(), nullable=False),
    sa.Column('game_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('game_clock', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('game_start_time', sa.DateTime(), nullable=True),
    sa.Column('game_end_time', sa.DateTime(), nullable=True),
    sa.Column('venue', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('game_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rivalry_factor', sa.Float(), nullable=True),
    sa.Column('broadcast_network', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attendance', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_index(op.f('ix_games_game_date'), 'games', ['game_date'], unique=False)
    op.create_index(op.f('ix_games_game_status'), 'games', ['game_status'], unique=False)
    op.create_index(op.f('ix_games_game_type'), 'games', ['game_type'], unique=False)
    op.create_index(op.f('ix_games_sport'), 'games', ['sport'], unique=False)
    op.create_index('idx_games_teams', 'games', ['home_team_id', 'away_team_id'], unique=False)
    op.create_table('team_rivalries',
    sa.Column('rivalry_id', sa.Integer(), nullable=False),
    sa.Column('team_a_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('team_b_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rivalry_factor', sa.Float(), nullable=False),
    sa.Column('rivalry_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_a_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['team_b_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('rivalry_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_rivalries')
    op.drop_index('idx_games_teams', table_name='games')
    op.drop_index(op.f('ix_games_sport'), table_name='games')
    op.drop_index(op.f('ix_games_game_type'), table_name='games')
    op.drop_index(op.f('ix_games_game_status'), table_name='games')
    op.drop_index(op.f('ix_games_game_date'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_teams_sport'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_team_groups_sport'), table_name='team_groups')
    op.drop_table('team_groups')
    # ### end Alembic commands ###
